services:
  - type: web
    name: caif
    runtime: docker
    repo: https://github.com/Rous444/caif-no-oficial
    plan: starter
    region: ohio
    disk:
      name: whatsapp-session
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caif-db
          property: connectionString
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        value: https://caif-wcb8.onrender.com
      - key: TZ
        value: America/Argentina/Buenos_Aires
      - key: DEFAULT_DOCTOR_PASSWORD
        value: MediCare2026!
      - key: DEFAULT_ADMIN_PASSWORD
        value: AdminMediCare2026!
      - key: WHATSAPP_SESSION_PATH
        value: /var/data

databases:
  - name: caif-db
    plan: free
    databaseName: medicare
    user: medicare
    region: ohio
